window.P1 = (function () {
  'use strict';

  const KATEGORI = [
    { id: 'k1',  nama: 'Cerita & Sejarah Ringan', label: ['CERITA', 'SEJARAH'],
      sub: 'Dari mana matematika bermula', jumlah: 10,
      color: '#63c8ff', deep: '#1c6fb4',
      ucap: ['Setiap angka', 'punya cerita!'] },
    { id: 'k2',  nama: 'Mengenal Angka', label: ['MENGENAL', 'ANGKA'],
      sub: 'Sahabat kecil 0 sampai 9', jumlah: 10,
      color: '#4fe3c8', deep: '#0d8a74',
      ucap: ['Angka itu', 'sahabatmu!'] },
    { id: 'k3',  nama: 'Simbol & Bahasa Matematika', label: ['SIMBOL', 'BAHASA'],
      sub: 'Tanda-tanda ajaib', jumlah: 10,
      color: '#ffd166', deep: '#c07d0c',
      ucap: ['Simbol itu', 'bahasa rahasia!'] },
    { id: 'k4',  nama: 'Penjumlahan & Pengurangan', label: ['TAMBAH', 'KURANG'],
      sub: 'Menggabung dan mencari sisa', jumlah: 12,
      color: '#7dffa8', deep: '#2aa85e',
      ucap: ['Tambah kurang,', 'gampang toh!'] },
    { id: 'k5',  nama: 'Perkalian & Pembagian', label: ['KALI', 'BAGI'],
      sub: 'Jurus hitung cepat', jumlah: 12,
      color: '#ff9d9d', deep: '#bd5a5f',
      ucap: ['Kali itu', 'tambah kilat!'] },
    { id: 'k6',  nama: 'Pecahan & Potongan Kue', label: ['PECAHAN', 'KUE'],
      sub: 'Bagian dari satu utuh', jumlah: 12,
      color: '#ffb86b', deep: '#c06a1c',
      ucap: ['Kue dibagi', 'sama rata ya!'] },
    { id: 'k7',  nama: 'Desimal, Persen & Uang', label: ['DESIMAL', 'UANG'],
      sub: 'Koma, persen, rupiah', jumlah: 10,
      color: '#f2b8cc', deep: '#c05a8a',
      ucap: ['Koma kecil,', 'makna besar!'] },
    { id: 'k8',  nama: 'Bentuk Pertama: Keliling & Luas', label: ['BENTUK', 'LUAS'],
      sub: 'Dunia bentuk di sekitar kita', jumlah: 10,
      color: '#bb8fff', deep: '#6a3fc0',
      ucap: ['Bentuk ada', 'di mana-mana!'] },
    { id: 'k9',  nama: 'Ukuran, Waktu & Takaran', label: ['UKURAN', 'WAKTU'],
      sub: 'Mengukur segala hal', jumlah: 6,
      color: '#c9f27a', deep: '#6aa31c',
      ucap: ['Semua bisa', 'diukur!'] },
    { id: 'k10', nama: 'Teka-Teki & Pola', label: ['TEKA-TEKI', 'POLA'],
      sub: 'Asah otak jadi jenius', jumlah: 8,
      color: '#d9c4ff', deep: '#8a63c9',
      ucap: ['Tebak-tebakan', 'asah otak!'] },
  ];

  const TOPIK = [

    { id: 'p1-001', k: 1, n: 1, judul: 'Matematika Itu Apa Sih?',
      teaser: 'Matematika itu ilmu mencari pola. Seperti mengenali langkah kaki sendiri: begitu polanya ketahuan, semua soal jadi terasa gampang.' },
    { id: 'p1-002', k: 1, n: 2, judul: 'Berhitung Zaman Batu',
      teaser: 'Dulu gembala menghitung domba pakai batu: satu batu untuk satu domba. Owalah, ternyata menghitung itu cuma menjodohkan satu-satu!' },
    { id: 'p1-003', k: 1, n: 3, judul: 'Kisah Al-Khawarizmi',
      teaser: 'Kenalan dengan ilmuwan Baitul Hikmah yang namanya jadi kata ALGORITMA. Setiap komputer mengikuti langkah rapi dari namanya.' },
    { id: 'p1-004', k: 1, n: 4, judul: 'Si Nol, Sang Pahlawan Kecil',
      teaser: 'Angka paling diam tapi paling berjasa. Tanpa nol, angka 100 cuma jadi 1 yang bingung berdiri di mana.' },
    { id: 'p1-005', k: 1, n: 5, judul: 'Piramida & Tali 3-4-5',
      teaser: 'Orang Mesir kuno memakai tali bermata 3-4-5 untuk membuat sudut tegak lurus. Piramida berdiri rapi berkat tali sederhana itu!' },
    { id: 'p1-006', k: 1, n: 6, judul: 'Angka Romawi yang Aneh',
      teaser: 'I, II, III, V, X... angka Romawi belum mengenal nol. Coba hitung pakai gaya Romawi, rasakan bedanya dengan angka kita.' },
    { id: 'p1-007', k: 1, n: 7, judul: 'Abakus, Kalkulator Kuno',
      teaser: 'Papan kelereng dari zaman dulu: geser ke atas, geser ke bawah, hitungan selesai. Kalkulator pertama di dunia ternyata sepele ya!' },
    { id: 'p1-008', k: 1, n: 8, judul: 'Kisah Pi yang Tak Selesai',
      teaser: 'Pi (π) itu 3,14 terus dan terus tanpa ujung. Angka paling setia: tak pernah berhenti menemani semua lingkaran.' },
    { id: 'p1-009', k: 1, n: 9, judul: 'Timbangan Pasar & Kejujuran',
      teaser: 'Timbangan jujur dan takaran tepat membuat jual beli adil untuk semua pihak. Matematika menjaga muamalah tetap bersih.' },
    { id: 'p1-010', k: 1, n: 10, judul: 'Matematika Teknologi',
      teaser: 'Dari roket sampai robot: semuanya terbang berkat hitungan. Teknologi hebat dimulai dari angka yang kamu pelajari hari ini.' },

    { id: 'p1-011', k: 2, n: 1, judul: 'Kenalan 0 Sampai 9',
      teaser: 'Sepuluh sahabat kecil yang bisa menulis semua angka di alam semesta. Cukup sepuluh, tidak kurang satu pun!' },
    { id: 'p1-012', k: 2, n: 2, judul: 'Berhitung Maju 1-10',
      teaser: 'Satu... dua... tiga... naik tangga angka. Tiap langkah naik satu anak tangga, sampai puncak sepuluh.' },
    { id: 'p1-013', k: 2, n: 3, judul: 'Berhitung Mundur 10-0',
      teaser: 'Sepuluh... sembilan... delapan... meluncur turun! Hitung mundur itu jurus wajib roket sebelum terbang.' },
    { id: 'p1-014', k: 2, n: 4, judul: 'Nilai Tempat: Puluhan',
      teaser: 'Angka 1 yang pindah ke depan bisa jadi 10! Posisi mengubah kekuatan angka, seperti kursi kapten di atas kapal.' },
    { id: 'p1-015', k: 2, n: 5, judul: 'Ratusan & Ribuan',
      teaser: 'Satu, sepuluh, seratus, seribu: tiap pindah satu kursi, kekuatannya membesar sepuluh kali. Hebat, bukan?' },
    { id: 'p1-016', k: 2, n: 6, judul: 'Angka Genap Berpasangan',
      teaser: 'Angka yang bisa berpasangan rapi: 2, 4, 6, 8... seperti sepatu yang selalu punya teman kakinya.' },
    { id: 'p1-017', k: 2, n: 7, judul: 'Angka Ganjil Sisa Satu',
      teaser: 'Angka yang selalu sisa satu saat berpasangan: 1, 3, 5, 7... seperti teman yang duduk sendiri tapi tetap seru.' },
    { id: 'p1-018', k: 2, n: 8, judul: 'Membandingkan Angka',
      teaser: 'Mana yang lebih banyak: 7 permen atau 9 permen? Belajar memilih lebih banyak dan lebih sedikit dengan yakin.' },
    { id: 'p1-019', k: 2, n: 9, judul: 'Urutan: Pertama & Kedua',
      teaser: 'Juara 1, juara 2, juara 3: angka bisa menunjukkan posisi, bukan cuma jumlah. Itu namanya bilangan urutan.' },
    { id: 'p1-020', k: 2, n: 10, judul: 'Pola Angka Naik',
      teaser: '+2, +2, +2: 2, 4, 6, 8. Angka suka berbaris dengan aturan. Tugasmu: temukan aturannya!' },

    { id: 'p1-021', k: 3, n: 1, judul: 'Tanda Tambah (+)',
      teaser: 'Tanda penggabung: permen di tangan kiri bertemu permen di tangan kanan. Plus itu ajakan berkumpul!' },
    { id: 'p1-022', k: 3, n: 2, judul: 'Tanda Kurang (−)',
      teaser: 'Tanda pemberangkat: permen yang dibawa pergi teman. Min itu tanda berkurang, bukan tanda sedih.' },
    { id: 'p1-023', k: 3, n: 3, judul: 'Tanda Kali (×)',
      teaser: 'Penjumlahan versi kilat: 3×4 artinya 4+4+4. Kali itu jurus singkat yang cerdas.' },
    { id: 'p1-024', k: 3, n: 4, judul: 'Tanda Bagi (÷)',
      teaser: 'Tanda pembagi rata: 8 kue untuk 2 anak, masing-masing dapat 4. Bagi itu seni berbagi yang adil.' },
    { id: 'p1-025', k: 3, n: 5, judul: 'Tanda Sama Dengan (=)',
      teaser: 'Timbangan ajaib: apa yang di kiri harus sama berat dengan di kanan. Itulah seluruh rahasia tanda =.' },
    { id: 'p1-026', k: 3, n: 6, judul: 'Lebih Besar & Kecil (> <)',
      teaser: 'Mulut buaya selalu lapar ke angka yang lebih besar. 9 > 3, nyam nyam!' },
    { id: 'p1-027', k: 3, n: 7, judul: 'Tanda Kurung ( )',
      teaser: 'Rumah spesial untuk angka: yang tinggal di dalam kurung dihitung duluan. Antri dengan rapi!' },
    { id: 'p1-028', k: 3, n: 8, judul: 'Tanda Koma Desimal',
      teaser: 'Koma itu pintu antara angka utuh dan kepingannya. Lewat pintu, mulailah bagian yang kecil-kecil.' },
    { id: 'p1-029', k: 3, n: 9, judul: 'Simbol Tak Hingga (∞)',
      teaser: 'Angka delapan yang tidur miring: ∞. Tandanya tidak ada habisnya, seperti langit tanpa dinding.' },
    { id: 'p1-030', k: 3, n: 10, judul: 'Membaca Kalimat Matematika',
      teaser: '2 + 3 = 5 itu kalimat lengkap: ada ceritanya, ada jawabannya. Matematika juga bisa dibaca seperti buku cerita!' },

    { id: 'p1-031', k: 4, n: 1, judul: 'Penjumlahan Pertama',
      teaser: '2 kelereng bertemu 3 kelereng jadi 5. Menggabungkan adalah dasar dari semua hitungan di dunia.' },
    { id: 'p1-032', k: 4, n: 2, judul: 'Berhitung dengan Jari',
      teaser: 'Sepuluh alat hitung bawaan lahir: jemari tanganmu. Angkat 3, angkat 4, hitung semuanya!' },
    { id: 'p1-033', k: 4, n: 3, judul: 'Menjumlah Lewat 10',
      teaser: '8 + 5: penuhi dulu sampai 10, sisanya ditumpuk di atas. Trik teman-teman pelengkap!' },
    { id: 'p1-034', k: 4, n: 4, judul: 'Penjumlahan Bersusun',
      teaser: 'Menyusun angka seperti barisan kecil: satuan di bawah satuan, puluhan di bawah puluhan. Rapi, tak ada yang tersesat.' },
    { id: 'p1-035', k: 4, n: 5, judul: 'Menyimpan ke Puluhan',
      teaser: 'Bila satuan penuh, satu naik ke tetangga atas: itu namanya menyimpan. Seperti titipan yang dijaga amanah.' },
    { id: 'p1-036', k: 4, n: 6, judul: 'Pengurangan Pertama',
      teaser: '5 kue, 2 dimakan: sisanya 3. Kurang itu mencari sisa, bukan kehilangan.' },
    { id: 'p1-037', k: 4, n: 7, judul: 'Pengurangan Bersusun',
      teaser: 'Kurang juga bisa disusun rapi seperti penjumlahan. Satuan lawan satuan, puluhan lawan puluhan.' },
    { id: 'p1-038', k: 4, n: 8, judul: 'Teknik Meminjam',
      teaser: 'Satuan kurang? Pinjam satu dari tetangga puluhan. Dipakai dengan bijak, hasilnya langsung jelas.' },
    { id: 'p1-039', k: 4, n: 9, judul: 'Keluarga Angka',
      teaser: '3+4=7, 4+3=7, 7−3=4, 7−4=3: satu keluarga, empat anggota. Hafal satu, kamu tahu empat!' },
    { id: 'p1-040', k: 4, n: 10, judul: 'Soal Cerita Tambah',
      teaser: 'Budi punya 4 layang-layang, ibu membeli 2 lagi. Berapa semuanya? Latihan mengubah cerita jadi hitungan.' },
    { id: 'p1-041', k: 4, n: 11, judul: 'Soal Cerita Kurang',
      teaser: 'Ada 7 permen, 3 dibagikan ke teman. Sisa berapa? Latihan menemukan pertanyaan tersembunyi dalam cerita.' },
    { id: 'p1-042', k: 4, n: 12, judul: 'Tantangan Tambah-Kurang',
      teaser: 'Angka hilang: 4 + ? = 9. Kini kamu detektif yang mencari pelaku kaburnya angka!' },

    { id: 'p1-043', k: 5, n: 1, judul: 'Kali Itu Tambah Cepat',
      teaser: '3×5 itu 5+5+5. Perkalian cuma penjumlahan yang diangkat jadi prajurit: lebih cepat, hasil sama persis.' },
    { id: 'p1-044', k: 5, n: 2, judul: 'Tabel Perkalian 2',
      teaser: '2, 4, 6, 8, 10... semua angka genap berbaris rapi. Tabel paling ramah untuk pemula.' },
    { id: 'p1-045', k: 5, n: 3, judul: 'Tabel Perkalian 5',
      teaser: 'Selalu berakhir 5 atau 0: 5, 10, 15, 20. Gampang diingat seperti deret jari tanganmu.' },
    { id: 'p1-046', k: 5, n: 4, judul: 'Tabel Perkalian 10',
      teaser: 'Cukup tambah nol di belakang: 10, 20, 30. Jurus paling gampang se-dunia perkalian.' },
    { id: 'p1-047', k: 5, n: 5, judul: 'Tabel Perkalian 3 & 4',
      teaser: '3, 6, 9, 12... lalu 4, 8, 12, 16... dua tabel sahabat. Naiki tangga kelipatan sambil bersenandung.' },
    { id: 'p1-048', k: 5, n: 6, judul: 'Tabel Perkalian 6-9',
      teaser: 'Kelompok tabel yang lebih dewasa. Sedikit berat memang — tapi berat itu tanda kamu naik kelas!' },
    { id: 'p1-049', k: 5, n: 7, judul: 'Trik Perkalian 9',
      teaser: 'Sembilan itu jenius: 9×3=27, lalu 2+7=9! Trik jarinya juga terkenal licin manis.' },
    { id: 'p1-050', k: 5, n: 8, judul: 'Perkalian Bersusun',
      teaser: '23×4: kalikan satuan, kalikan puluhan, lalu kumpulkan. Karya besar dibangun dari langkah kecil yang rapi.' },
    { id: 'p1-051', k: 5, n: 9, judul: 'Bagi Itu Membagi Rata',
      teaser: '10 kelereng untuk 2 anak: masing-masing 5. Pembagian adalah ilmu adil yang belajar sejak kecil.' },
    { id: 'p1-052', k: 5, n: 10, judul: 'Pembagian dengan Sisa',
      teaser: '7 kue untuk 2 anak: masing-masing 3, sisa 1. Sisa itu bukan salah — dia cuma menunggu giliran berikutnya.' },
    { id: 'p1-053', k: 5, n: 11, judul: 'Pembagian Bersusun',
      teaser: 'Pembagian panjang: turunkan angka satu per satu. Seperti menuruni tangga sambil terus menghitung.' },
    { id: 'p1-054', k: 5, n: 12, judul: 'Tantangan Kali-Bagi',
      teaser: 'Kali dan bagi saling membongkar rahasia: 6×4=24, maka 24÷6=4. Mereka pasangan setia seumur hidup!' },

    { id: 'p1-055', k: 6, n: 1, judul: 'Setengah Itu 1/2',
      teaser: 'Satu kue dibagi dua sama besar: tiap bagian bernilai setengah. Adil itu indah sejak potongan pertama.' },
    { id: 'p1-056', k: 6, n: 2, judul: 'Seperempat Itu 1/4',
      teaser: 'Empat potongan sama besar, ambil satu: itulah seperempat. Seperti potongan kue ulang tahun di piringmu.' },
    { id: 'p1-057', k: 6, n: 3, judul: 'Pembilang & Penyebut',
      teaser: 'Di 3/4: angka atas bilang berapa bagian diambil, angka bawah bilang kue dibagi berapa. Nama saja, bukan sulit!' },
    { id: 'p1-058', k: 6, n: 4, judul: 'Keluarga Pecahan 1/n',
      teaser: 'Dibagi 3, 5, atau 100: itu keluarga pecahan satu-per-n. Makin banyak pembagi, makin kecil potongannya.' },
    { id: 'p1-059', k: 6, n: 5, judul: 'Pecahan Senilai',
      teaser: '1/2 = 2/4 = 3/6: ukurannya sama, namanya beda. Seperti dipanggil Kak, Bang, atau Abang — orangnya tetap sama!' },
    { id: 'p1-060', k: 6, n: 6, judul: 'Membandingkan Pecahan',
      teaser: '1/2 atau 1/8 mana yang besar? Hati-hati, pecahan suka memasang jebak: makin kecil penyebut, makin besar potongannya!' },
    { id: 'p1-061', k: 6, n: 7, judul: 'Menjumlah Pecahan Senama',
      teaser: '1/4 + 2/4 = 3/4: potongan sejenis gampang digabung. Ibarat menggabung potongan kue di piring yang sama.' },
    { id: 'p1-062', k: 6, n: 8, judul: 'Kurang Pecahan Senama',
      teaser: '3/4 − 1/4 = 2/4. Mengambil satu potongan dari piring, sisanya tinggal dihitung santai.' },
    { id: 'p1-063', k: 6, n: 9, judul: 'Pecahan Campuran',
      teaser: 'Satu kue utuh plus setengah: 1½. Kadang kue tidak habis dalam satu porsi, dan itu sama sekali bukan masalah.' },
    { id: 'p1-064', k: 6, n: 10, judul: 'Bagian dari Banyak',
      teaser: '½ dari 10 kelereng sama dengan 5. Ternyata pecahan bisa menyentuh benda utuh, bukan cuma kue!' },
    { id: 'p1-065', k: 6, n: 11, judul: 'Menggambar Pecahan',
      teaser: 'Warnai 2 dari 4 bagian: kamu baru saja menggambar 2/4. Menggambar adalah cara tergampang memahami pecahan.' },
    { id: 'p1-066', k: 6, n: 12, judul: 'Tantangan Potongan Kue',
      teaser: 'Kue dibagi 8, dimakan 3, lalu sisanya dibagi dua... siap? Kuis pecahan paling menggoda di seluruh kamp!' },

    { id: 'p1-067', k: 7, n: 1, judul: 'Kenalan Angka Koma',
      teaser: '0,5 itu sahabat dekat 1/2. Angka di belakang koma adalah potongan kecil dari satu utuh.' },
    { id: 'p1-068', k: 7, n: 2, judul: 'Persepuluhan 0,1',
      teaser: 'Satu utuh dibagi 10: tiap keping bernilai 0,1. Seperti satu bilik dari 10 bilik kandang.' },
    { id: 'p1-069', k: 7, n: 3, judul: 'Desimal & Pecahan Saudara',
      teaser: '0,25 = 1/4 dan 0,5 = 1/2: dua bahasa untuk satu arti. Kamu kini dwibahasa matematika!' },
    { id: 'p1-070', k: 7, n: 4, judul: 'Membandingkan Desimal',
      teaser: '0,7 atau 0,25 mana yang besar? Jangan tertipu oleh panjang angka! Lihat dulu angka pertama setelah koma.' },
    { id: 'p1-071', k: 7, n: 5, judul: 'Persen Itu Apa?',
      teaser: 'Persen berarti "dari 100". 25% = 25 dari 100 = seperempat. Tanda % itu saudara jauh pecahan.' },
    { id: 'p1-072', k: 7, n: 6, judul: 'Persen Favorit 50%',
      teaser: '50% itu setengah, 100% itu utuh, 0% sudah habis. Persen menyederhanakan cerita panjang jadi satu kata.' },
    { id: 'p1-073', k: 7, n: 7, judul: 'Tiga Rupa Satu Makna',
      teaser: '1/2 = 0,5 = 50%: tiga rupa, satu makna. Kamu kini memegang tiga kunci untuk satu pintu yang sama.' },
    { id: 'p1-074', k: 7, n: 8, judul: 'Kenalan Uang Rupiah',
      teaser: 'Seribu, dua ribu, lima ribu: nilai uang berlapis-lapis. Uang adalah angka yang bisa dipegang tangan.' },
    { id: 'p1-075', k: 7, n: 9, judul: 'Belanja & Kembalian',
      teaser: 'Bayar 5.000, belanja 3.000, kembalian 2.000. Menghitung kembalian adalah latihan pengurangan paling seru sedunia!' },
    { id: 'p1-076', k: 7, n: 10, judul: 'Menabung Seribu',
      teaser: 'Menyisihkan sedikit tiap hari: 500+500+500 jadi 1.500. Tabungan adalah matematika yang sabar dan menolong.' },

    { id: 'p1-077', k: 8, n: 1, judul: 'Dunia Bentuk Datar',
      teaser: 'Kotak, lingkaran, segitiga: bentuk-bentuk itu menempel di mana-mana. Jendela, piring, roda sepeda!' },
    { id: 'p1-078', k: 8, n: 2, judul: 'Garis, Sisi & Sudut',
      teaser: 'Garis lurus dan tikungan: bentuk dibangun dari sisi-sisi yang bertemu. Sudut adalah tikungan antar sisi.' },
    { id: 'p1-079', k: 8, n: 3, judul: 'Keliling Itu Jalan Keliling',
      teaser: 'Keliling = berjalan menyusuri pinggir bentuk sampai kembali ke titik awal. Seperti keliling lapangan satu putaran penuh.' },
    { id: 'p1-080', k: 8, n: 4, judul: 'Keliling Persegi Panjang',
      teaser: '(panjang + lebar) × 2: dua jalan panjang plus dua jalan pendek. Rumus hanyalah cerita yang dipersingkat!' },
    { id: 'p1-081', k: 8, n: 5, judul: 'Luas Itu Pasang Ubin',
      teaser: 'Luas = berapa ubin persegi untuk menutup lantai. Keliling itu pagar, luas itu karpet. Bedanya di situ!' },
    { id: 'p1-082', k: 8, n: 6, judul: 'Luas Persegi Panjang',
      teaser: 'panjang × lebar: baris kali kolom. Menghitung seluruh ubin tanpa memasangnya satu per satu.' },
    { id: 'p1-083', k: 8, n: 7, judul: 'Segitiga Setengah Kotak',
      teaser: 'Luas segitiga = ½ × alas × tinggi: segitiga itu setengah persegi panjang yang menyampir. Owalah, ternyata begitu!' },
    { id: 'p1-084', k: 8, n: 8, judul: 'Lingkaran Si Bulat',
      teaser: 'Lingkaran tak punya sudut: ada pusat, jari-jari, dan keliling yang dijaga Pi. Roda berputar rapi berkat bentuk ini.' },
    { id: 'p1-085', k: 8, n: 9, judul: 'Kenalan Kubus & Balok',
      teaser: 'Bentuk 3D punya isi: kardus, dadu, lemari. Dunia datar naik kelas menjadi dunia yang berisi.' },
    { id: 'p1-086', k: 8, n: 10, judul: 'Detektif Bentuk di Sekitar',
      teaser: 'Misi: temukan 5 bentuk di kamarmu malam ini! Setelah pelajaran ini, duniamu tampak penuh matematika.' },

    { id: 'p1-087', k: 9, n: 1, judul: 'Panjang: cm & m',
      teaser: 'Jari kelingking kira-kira 1 cm, satu langkah besar kira-kira 1 m. Penggaris adalah alat ukur paling setia.' },
    { id: 'p1-088', k: 9, n: 2, judul: 'Berat: gram & kg',
      teaser: 'Selembar kertas ± 5 gram, sebungkus gula 1 kg. Timbangan yang jujur tidak bisa dibohongi.' },
    { id: 'p1-089', k: 9, n: 3, judul: 'Takaran: liter & ml',
      teaser: 'Segelas air ± 250 ml, empat gelas jadi 1 liter. Memasak di dapur adalah laboratorium takaran!' },
    { id: 'p1-090', k: 9, n: 4, judul: 'Jam & Menit',
      teaser: 'Jarum panjang menghitung menit, jarum pendek menghitung jam. 60 menit = 1 jam: warisan Babilonia yang setia.' },
    { id: 'p1-091', k: 9, n: 5, judul: 'Hari, Minggu & Kalender',
      teaser: '7 hari satu minggu, kira-kira 30 hari satu bulan. Kalender adalah buku catatan waktu yang rapi.' },
    { id: 'p1-092', k: 9, n: 6, judul: 'Panas & Dingin: Suhu',
      teaser: 'Derajat mengukur panas dan dingin: air membeku di 0°, mendidih di 100°. Termometer itu jam-nya suhu.' },

    { id: 'p1-093', k: 10, n: 1, judul: 'Pola Berulang',
      teaser: 'Merah-biru-merah-biru... pola itu aturan yang berulang. Menemukan pola = menemukan jalan pintas berpikir.' },
    { id: 'p1-094', k: 10, n: 2, judul: 'Angka yang Hilang',
      teaser: '2, 4, ?, 8: siapa yang kabur? Detektif angka menemukan pelarinya dengan mengenali polanya.' },
    { id: 'p1-095', k: 10, n: 3, judul: 'Kotak Ajaib Angka',
      teaser: 'Susun angka agar tiap baris dan tiap kolom sama jumlahnya. Kotak ajaib: teka-teki tua yang masih memukau.' },
    { id: 'p1-096', k: 10, n: 4, judul: 'Hitung Cepat di Kepala',
      teaser: '99 + 17 = 100 + 16 = 116! Geser sedikit, hitungan jadi ringan. Matematika itu seni jalan pintas yang sah.' },
    { id: 'p1-097', k: 10, n: 5, judul: 'Labirin Angka',
      teaser: 'Jalan hanya boleh lewat kelipatan 3: 3, 6, 9... Labirin mengajarkan aturan sambil bermain.' },
    { id: 'p1-098', k: 10, n: 6, judul: 'Logika Si A & Si B',
      teaser: 'Si A lebih tinggi dari B, si B lebih tinggi dari C. Lalu siapa yang tertinggi? Logika: hitungan yang berpikir.' },
    { id: 'p1-099', k: 10, n: 7, judul: 'Sudoku Mini 4x4',
      teaser: 'Tiap baris, kolom, dan kotak harus berisi 1 sampai 4 tanpa ulang. Sudoku: mainan aturan paling populer sedunia.' },
    { id: 'p1-100', k: 10, n: 8, judul: 'Tantangan Juara Kamp',
      teaser: 'Campuran semua teka-teki Pintu 1 dalam satu ajang. Siapkan jari dan kepala: gelar Juara Kamp menantimu!' },
  ];

  function topikKategori(k) { return TOPIK.filter(t => t.k === k); }
  function katById(id) { return KATEGORI.find(k => k.id === id) || null; }
  function topikById(id) { return TOPIK.find(t => t.id === id) || null; }
  function topikLain(id, arah) {
    const t = topikById(id);
    if (!t) return null;
    const daftar = topikKategori(t.k);
    const i = daftar.findIndex(x => x.id === id);
    return daftar[i + arah] || null;
  }

  return { KATEGORI, TOPIK, topikKategori, katById, topikById, topikLain };
})();
