/* =========================================================
   PINTU 2 — HUTAN SIMBOL: DATA 100 JUDUL (pintu2-data.js)
   Isi dunia Pintu 2: 10 penjuru (kategori) berisi 100 judul.
   Struktur & helper sama persis dengan pintu1-data.js agar
   mesin pelajaran.html bisa melayani kedua pintu.
   Wilayah: bahasa dan tanda — bilangan negatif, faktor,
   aljabar, persamaan, rasio, sudut, isi ruang, koordinat,
   statistika, peluang.
   Syariah: semua contoh netral & muamalah adil.
   ========================================================= */
window.P2 = (function () {
  'use strict';

  /* ---------- 10 penjuru hutan ---------- */
  const KATEGORI = [
    { id: 'k1',  nama: 'Bilangan Negatif', label: ['BILANGAN', 'NEGATIF'],
      sub: 'Angka di bawah nol', jumlah: 10,
      color: '#4fe3c8', deep: '#0d8a74',
      ucap: ['Lebih kecil', 'dari nol!'] },
    { id: 'k2',  nama: 'Faktor, FPB & KPK', label: ['FAKTOR', 'FPB KPK'],
      sub: 'Memecah dan memasangkan bilangan', jumlah: 10,
      color: '#7dffa8', deep: '#2aa85e',
      ucap: ['Pecah bilangan,', 'temukan pola!'] },
    { id: 'k3',  nama: 'Aljabar Pertama', label: ['ALJABAR', 'HURUF'],
      sub: 'Huruf yang mewakili bilangan', jumlah: 10,
      color: '#ffd166', deep: '#c07d0c',
      ucap: ['Huruf bisa', 'jadi angka!'] },
    { id: 'k4',  nama: 'Persamaan & Pertidaksamaan', label: ['PERSAMAAN', 'NILAI X'],
      sub: 'Mencari nilai yang hilang', jumlah: 10,
      color: '#ff9d9d', deep: '#bd5a5f',
      ucap: ['Cari nilai', 'yang hilang!'] },
    { id: 'k5',  nama: 'Rasio, Skala & Proporsi', label: ['RASIO', 'SKALA'],
      sub: 'Perbandingan yang adil', jumlah: 10,
      color: '#63c8ff', deep: '#1c6fb4',
      ucap: ['Bandingkan', 'secukupnya!'] },
    { id: 'k6',  nama: 'Sudut & Pythagoras', label: ['SUDUT', 'PYTHAGORAS'],
      sub: 'Bukaan, garis, dan sisi miring', jumlah: 10,
      color: '#bb8fff', deep: '#6a3fc0',
      ucap: ['Sudut ada', 'di mana-mana!'] },
    { id: 'k7',  nama: 'Luas Permukaan & Volume', label: ['LUAS', 'VOLUME'],
      sub: 'Bentuk yang punya isi', jumlah: 10,
      color: '#ffb86b', deep: '#c06a1c',
      ucap: ['Bentuk punya', 'isi ruang!'] },
    { id: 'k8',  nama: 'Koordinat & Grafik Pertama', label: ['KOORDINAT', 'GRAFIK'],
      sub: 'Setiap titik punya alamat', jumlah: 10,
      color: '#f2b8cc', deep: '#c05a8a',
      ucap: ['Titik punya', 'alamat!'] },
    { id: 'k9',  nama: 'Statistika Kecil', label: ['DATA', 'RERATA'],
      sub: 'Data bercerita', jumlah: 10,
      color: '#c9f27a', deep: '#6aa31c',
      ucap: ['Data bercerita', 'jika dibaca!'] },
    { id: 'k10', nama: 'Peluang Dasar', label: ['PELUANG', 'DASAR'],
      sub: 'Menghitung kemungkinan', jumlah: 10,
      color: '#d9c4ff', deep: '#8a63c9',
      ucap: ['Hitung', 'kemungkinannya!'] },
  ];

  /* ---------- 100 judul (k = penjuru 1..10, n = nomor di penjuru) ---------- */
  const TOPIK = [
    /* --- k1: Bilangan Negatif (10) --- */
    { id: 'p2-001', k: 1, n: 1, judul: 'Angka di Bawah Nol',
      teaser: 'Ada angka yang lebih kecil dari nol: −1, −2, −3. Seperti lantai bawah tanah di gedung besar — makin turun, makin dalam.' },
    { id: 'p2-002', k: 1, n: 2, judul: 'Garis Bilangan Dua Arah',
      teaser: 'Bayangkan jalan lurus: nol di tengah, ke kanan 1, 2, 3, ke kiri −1, −2, −3. Dua arah, tanpa ujung!' },
    { id: 'p2-003', k: 1, n: 3, judul: 'Suhu di Bawah Nol',
      teaser: 'Termometer bisa menunjukkan −5 derajat: tanda udara lebih dingin dari air es. Makin jauh turun, makin dingin.' },
    { id: 'p2-004', k: 1, n: 4, judul: 'Utang & Saldo',
      teaser: 'Saldo −3 artinya kurang tiga: ibarat utang tiga permen yang menunggu diganti. Angka negatif jujur tentang kekurangan.' },
    { id: 'p2-005', k: 1, n: 5, judul: 'Membandingkan Negatif',
      teaser: 'Mana lebih dingin: −8 atau −3? Hati-hati, −8 lebih panjang tulisannya tapi justru nilainya lebih kecil. Garis bilangan tak bisa bohong!' },
    { id: 'p2-006', k: 1, n: 6, judul: 'Jalan Maju & Mundur',
      teaser: '3 + (−5) artinya maju 3 langkah lalu mundur 5 langkah: kaki mendarat di −2. Tambah dengan negatif itu jalan mundur.' },
    { id: 'p2-007', k: 1, n: 7, judul: 'Kurang yang Membalik',
      teaser: '3 − (−2) = 5: mengurangkan negatif seperti membuka pintu balik — dua tanda minus bertemu, arah justru maju!' },
    { id: 'p2-008', k: 1, n: 8, judul: 'Dua Balikan Jadi Positif',
      teaser: '(−2) × (−3) = 6. Membalik arah dua kali sama dengan kembali ke arah semula. Kejutan paling manis dari bilangan negatif.' },
    { id: 'p2-009', k: 1, n: 9, judul: 'Aturan Tanda Pembagian',
      teaser: '(−6) ÷ 2 = −3, tapi (−6) ÷ (−2) = 3. Tanda yang sama melahirkan positif, tanda yang beda melahirkan negatif.' },
    { id: 'p2-010', k: 1, n: 10, judul: 'Tantangan Lantai Bawah',
      teaser: 'Lift tambang penuh soal: turun berapa lantai, dingin berapa derajat? Selesaikan semua untuk membuka gerbang paling dalam!' },

    /* --- k2: Faktor, FPB & KPK (10) --- */
    { id: 'p2-011', k: 2, n: 1, judul: 'Faktor: Pasangan Pengali',
      teaser: '12 bisa jadi 1×12, 2×6, atau 3×4. Pasangan itu namanya faktor: pembagi yang membuat sisa nol.' },
    { id: 'p2-012', k: 2, n: 2, judul: 'Faktorisasi Prima',
      teaser: 'Pecah bilangan sampai tinggal bata prima: 12 = 2 × 2 × 3. Bilangan prima adalah bata terakhir yang tak bisa dipecah lagi.' },
    { id: 'p2-013', k: 2, n: 3, judul: 'FPB: Faktor Bersama Terbesar',
      teaser: 'FPB 12 dan 18 adalah 6: pembagi terbesar yang dimiliki keduanya, seperti kotak terbesar yang membagi dua kelompok sama rata.' },
    { id: 'p2-014', k: 2, n: 4, judul: 'KPK: Kelipatan Bersama',
      teaser: 'Lampu menyala tiap 4 detik dan tiap 6 detik: kapan menyala bersama? Di detik 12! Itulah KPK.' },
    { id: 'p2-015', k: 2, n: 5, judul: 'Jurus Tabel Prima',
      teaser: 'Susun pembagian bertingkat: turunkan, bagi lagi, sampai satu. Rapi dan tak ada faktor yang lupa.' },
    { id: 'p2-016', k: 2, n: 6, judul: 'FPB dari Faktorisasi',
      teaser: 'Ambil prima yang sama dari dua bilangan, kalikan yang terkecil. Dari 2×2×3 dan 2×3×3 lahirlah FPB 6.' },
    { id: 'p2-017', k: 2, n: 7, judul: 'KPK dari Faktorisasi',
      teaser: 'Ambil semua prima, pilih pangkat tertinggi, kalikan. Jurus ini menemukan KPK tanpa menebak-nebak.' },
    { id: 'p2-018', k: 2, n: 8, judul: 'Menyederhanakan Pecahan',
      teaser: '12/18 dibagi FPB 6 menjadi 2/3. Pecahan rapi lebih mudah dibaca — seperti kamar yang barusan diurapikan.' },
    { id: 'p2-019', k: 2, n: 9, judul: 'Samakan Penyebut',
      teaser: '1/4 dan 1/6 bertemu di penyebut 12 berkat KPK. Setelah sama, penjumlahan pecahan jadi sangat tenang.' },
    { id: 'p2-020', k: 2, n: 10, judul: 'Tantangan Detektif Faktor',
      teaser: 'Bilangan mana habis dibagi 3? Mana pasangan koprima? Buktikan ketelitianmu di penjuru paling teliti ini.' },

    /* --- k3: Aljabar Pertama (10) --- */
    { id: 'p2-021', k: 3, n: 1, judul: 'Huruf Pengganti Angka',
      teaser: 'x itu kotak misteri yang menampung bilangan. Begitu isinya ketahuan, kotak dibuka dan jawaban muncul.' },
    { id: 'p2-022', k: 3, n: 2, judul: 'Suku Sejenis Berkumpul',
      teaser: '2x + 3x = 5x: apel dengan apel, jeruk dengan jeruk. Suku sejenis boleh digabung, beda jenis tetap dipisah.' },
    { id: 'p2-023', k: 3, n: 3, judul: 'Mengali Bentuk Aljabar',
      teaser: '3 × 2x = 6x: angka di depan disebut koefisien, dan koefisien ikut terkali seluruhnya.' },
    { id: 'p2-024', k: 3, n: 4, judul: 'Membuka Kurung',
      teaser: '2(x + 3) = 2x + 6: angka di luar kurung menyapa setiap anggota di dalam, tak ada yang terlewat.' },
    { id: 'p2-025', k: 3, n: 5, judul: 'Menyisipkan Nilai',
      teaser: 'Kalau x = 4, maka 2x + 1 = 9. Ganti huruf dengan bilangan, lalu hitung: itu namanya substitusi.' },
    { id: 'p2-026', k: 3, n: 6, judul: 'Merapikan Bentuk Panjang',
      teaser: '5x − 2 + 3x + 4 dirapikan jadi 8x + 2. Kumpulkan yang sejenis, jumlahkan yang bisa dijumlah.' },
    { id: 'p2-027', k: 3, n: 7, judul: 'Pola Jadi Rumus',
      teaser: 'Barisan 3, 7, 11, 15 naik 4 tiap langkah. Rumusnya 4n − 1: pola yang panjang muat dalam satu baris.' },
    { id: 'p2-028', k: 3, n: 8, judul: 'Koefisien & Konstanta',
      teaser: 'Di 3x + 5: angka 3 menempel pada x, sedangkan 5 berdiri sendiri. Yang berdiri sendiri itu konstanta.' },
    { id: 'p2-029', k: 3, n: 9, judul: 'Membaca Bentuk Aljabar',
      teaser: '2a + 3b artinya dua kelompok a dan tiga kelompok b. Bentuk aljabar adalah kalimat singkat tentang banyak bilangan.' },
    { id: 'p2-030', k: 3, n: 10, judul: 'Tantangan Rumus Hutan',
      teaser: 'Temukan rumus barisan, buka kurung bersarang, gabungkan suku. Penjuru aljabar menguji kerapian berpikirmu.' },

    /* --- k4: Persamaan & Pertidaksamaan (10) --- */
    { id: 'p2-031', k: 4, n: 1, judul: 'Timbangan Persamaan',
      teaser: 'x + 3 = 7 adalah timbangan seimbang. Bila sisi kiri berubah, sisi kanan harus ikut agar tetap pas.' },
    { id: 'p2-032', k: 4, n: 2, judul: 'Mencari Nilai x',
      teaser: 'x + 3 = 7, maka x = 4: geser +3 ke seberang berubah jadi −3. Langkah pertama detektif persamaan.' },
    { id: 'p2-033', k: 4, n: 3, judul: 'Kali & Bagi pada x',
      teaser: '2x = 10, maka x = 5. Yang dikali di kiri, dibagi di kanan: timbangan tetap seimbang.' },
    { id: 'p2-034', k: 4, n: 4, judul: 'Persamaan Dua Langkah',
      teaser: '2x + 3 = 11: kurangi dulu 3, lalu bagi 2, bertemulah x = 4. Langkah pelan, jawaban pasti.' },
    { id: 'p2-035', k: 4, n: 5, judul: 'x di Dua Sisi',
      teaser: '3x + 2 = x + 10: kumpulkan semua x di satu sisi, angka di sisi lain. Timbangan besar tetap berdiri.' },
    { id: 'p2-036', k: 4, n: 6, judul: 'Memeriksa Jawaban',
      teaser: 'Masukkan kembali nilai x ke persamaan awal: kalau kiri sama kanan, jawabanmu sahih. Detektif selalu membuktikan!' },
    { id: 'p2-037', k: 4, n: 7, judul: 'Lebih dari & Kurang dari',
      teaser: 'x > 3 artinya x lebih besar dari 3; x < 3 berarti lebih kecil. Pertidaksamaan bicara tentang arah.' },
    { id: 'p2-038', k: 4, n: 8, judul: 'Garis Pertidaksamaan',
      teaser: 'Panahkan garis bilangan ke kanan dari 3 untuk x > 3: semua titik di panah adalah jawaban. Banyak, bukan satu!' },
    { id: 'p2-039', k: 4, n: 9, judul: 'Pertidaksamaan Dua Langkah',
      teaser: '2x + 1 < 9: kurangi 1 lalu bagi 2, jadi x < 4. Aturannya setia pada persamaan, ujungnya berupa panah.' },
    { id: 'p2-040', k: 4, n: 10, judul: 'Tantangan Timbangan Hutan',
      teaser: 'Persamaan bersusun dan pertidaksamaan menantimu. Selesaikan, periksa kembali, dan buka gerbang terakhir.' },

    /* --- k5: Rasio, Skala & Proporsi (10) --- */
    { id: 'p2-041', k: 5, n: 1, judul: 'Rasio: Perbandingan',
      teaser: '2 : 3 dibaca dua banding tiga: perbandingan dua kelompok. Seperti adonan: 2 takaran tepung untuk 3 takaran air.' },
    { id: 'p2-042', k: 5, n: 2, judul: 'Skala Peta',
      teaser: 'Skala 1 : 1000 artinya 1 langkah di peta mewakili 1.000 langkah di jalan sebenarnya. Peta kecil, dunia besar.' },
    { id: 'p2-043', k: 5, n: 3, judul: 'Harga Satuan',
      teaser: '6 permen harganya 3.000: berapa satu permen? Bagi rata, jadilah 500. Harga satuan memudahkan membandingkan.' },
    { id: 'p2-044', k: 5, n: 4, judul: 'Proporsi Tetap Setia',
      teaser: 'Resep 2 : 3 digandakan jadi 4 : 6 — rasanya tetap sama. Proporsi adalah rasio yang setia walau jumlah membesar.' },
    { id: 'p2-045', k: 5, n: 5, judul: 'Kecepatan & Waktu',
      teaser: 'Melaju 60 km tiap jam: 1 jam 60 km, 2 jam 120 km. Kecepatan merangkai jarak dan waktu dengan rasio rapi.' },
    { id: 'p2-046', k: 5, n: 6, judul: 'Rasio Bertemu Persen',
      teaser: '3 dari 4 bagian sama dengan 75 persen. Rasio, pecahan, dan persen: tiga bahasa untuk satu perbandingan.' },
    { id: 'p2-047', k: 5, n: 7, judul: 'Skala Miniatur',
      teaser: 'Mobil mainan skala 1 : 24 berarti aslinya 24 kali lebih panjang. Ukur mainanmu, kali 24, ketahuan ukurannya!' },
    { id: 'p2-048', k: 5, n: 8, judul: 'Berbalik Nilai',
      teaser: 'Makin banyak pekerja, makin cepat selesai: 4 pekerja 6 hari, 8 pekerja 3 hari. Ada rasio yang saling menurunkan.' },
    { id: 'p2-049', k: 5, n: 9, judul: 'Resep & Takaran',
      teaser: 'Menambah tamu berarti menggandakan takaran. Dapur adalah tempat latihan proporsi paling lezat sedunia.' },
    { id: 'p2-050', k: 5, n: 10, judul: 'Tantangan Skala Hutan',
      teaser: 'Peta harta karun berskala, resep ganda, harga satuan: buktikan rasiomu jadi jurus paling tajam.' },

    /* --- k6: Sudut & Pythagoras (10) --- */
    { id: 'p2-051', k: 6, n: 1, judul: 'Mengenal Sudut',
      teaser: 'Sudut adalah bukaan antara dua garis yang bertemu: lancip sempit, siku pas 90 derajat, tumpul terbuka lebar.' },
    { id: 'p2-052', k: 6, n: 2, judul: 'Sudut Garis Lurus',
      teaser: 'Dua sudut di garis lurus selalu berjumlah 180 derajat. Bila satu 110, pasangannya pasti 70 — selamanya berdua.' },
    { id: 'p2-053', k: 6, n: 3, judul: 'Sudut Bertemu di Titik',
      teaser: 'Semua sudut yang berkumpul di satu titik berjumlah 360 derajat — sama dengan satu putaran penuh.' },
    { id: 'p2-054', k: 6, n: 4, judul: 'Rahasia Segitiga',
      teaser: 'Tiga sudut segitiga, bagaimanapun bentuknya, selalu berjumlah 180 derajat. Robek kertas dan buktikan sendiri!' },
    { id: 'p2-055', k: 6, n: 5, judul: 'Segiempat & Sudutnya',
      teaser: 'Persegi dan persegi panjang sama-sama memuat empat sudut siku. Jumlah sudut segiempat selalu 360 derajat.' },
    { id: 'p2-056', k: 6, n: 6, judul: 'Garis Sejajar Terpotong',
      teaser: 'Dua garis sejajar dipotong garis miring: sudut-sudutnya berpasangan sama besar. Pola rapi di rel kereta!' },
    { id: 'p2-057', k: 6, n: 7, judul: 'Teorema Pythagoras',
      teaser: 'Di segitiga siku-siku: alas persegi ditambah tinggi persegi sama dengan sisi miring persegi. Konon dipakai tukang bangun sejak kuno.' },
    { id: 'p2-058', k: 6, n: 8, judul: 'Segitiga Andalan 3-4-5',
      teaser: 'Sisi 3, 4, dan 5 membuat sudut sempurna: 3×3 + 4×4 = 5×5. Tali bermata 3-4-5 jadi andalan tukang bangun berabad-abad.' },
    { id: 'p2-059', k: 6, n: 9, judul: 'Mencari Sisi yang Hilang',
      teaser: 'Sisi miring 10, alas 6: tinggi persegi 100 − 36 = 64, maka sisi hilangnya 8. Pythagoras pencari yang hilang.' },
    { id: 'p2-060', k: 6, n: 10, judul: 'Tantangan Sudut Hutan',
      teaser: 'Ukur sudut, buktikan 180 derajat, dan selesaikan segitiga siku-siku. Penjuru geometri menunggu detektif sudut.' },

    /* --- k7: Luas Permukaan & Volume (10) --- */
    { id: 'p2-061', k: 7, n: 1, judul: 'Kubus: Sisi & Isi',
      teaser: 'Kubus punya 6 sisi persegi sama besar. Luas permukaan 6 × sisi × sisi; volumenya sisi × sisi × sisi.' },
    { id: 'p2-062', k: 7, n: 2, judul: 'Balok & Permukaannya',
      teaser: 'Balok punya 6 sisi yang tersusun 3 pasang kembar. Jumlahkan luas semuanya, tak ada yang tertinggal.' },
    { id: 'p2-063', k: 7, n: 3, judul: 'Volume Balok',
      teaser: 'panjang × lebar × tinggi: menghitung berapa kubus satuan yang muat mengisi. Isi ruang tumbuh lapis demi lapis.' },
    { id: 'p2-064', k: 7, n: 4, judul: 'Prisma Segitiga',
      teaser: 'Prisma segitiga seperti atap rumah: luas alas segitiga dikalikan tinggi prisma menghasilkan isi ruangnya.' },
    { id: 'p2-065', k: 7, n: 5, judul: 'Tabung: Si Kaleng',
      teaser: 'Tabung punya dua tutup lingkaran dan selimut tergulung. Buka label kaleng: terbentang persegi panjang!' },
    { id: 'p2-066', k: 7, n: 6, judul: 'Luas Selimut Tabung',
      teaser: 'Keliling lingkaran × tinggi sama dengan luas selimut. Label kaleng memang persegi panjang yang digulung.' },
    { id: 'p2-067', k: 7, n: 7, judul: 'Kenalan Kerucut & Bola',
      teaser: 'Kerucut seperti topi ulang tahun, bola seperti bola sepak: keduanya bulat dan punya isi ruang.' },
    { id: 'p2-068', k: 7, n: 8, judul: 'Liter & Sentimeter Kubik',
      teaser: '1 liter sama dengan 1.000 sentimeter kubik. Satuan isi itu saudara: kubus kecil berjuta-juta menampung air.' },
    { id: 'p2-069', k: 7, n: 9, judul: 'Mengukur Isi Benda Nyata',
      teaser: 'Akuarium, ember, dan botol: ukur lalu hitung volumenya. Dunia penuh benda berisi yang menunggu dihitung.' },
    { id: 'p2-070', k: 7, n: 10, judul: 'Tantangan Gudang Bentuk',
      teaser: 'Kardus mana yang paling banyak berisi? Susun, ukur, bandingkan — jadilah mandor gudang paling teliti.' },

    /* --- k8: Koordinat & Grafik Pertama (10) --- */
    { id: 'p2-071', k: 8, n: 1, judul: 'Sumbu X & Sumbu Y',
      teaser: 'Dua garis berpotongan di nol: mendatar bernama sumbu x, tegak bernama sumbu y. Kini semua titik punya alamat.' },
    { id: 'p2-072', k: 8, n: 2, judul: 'Membaca Titik (x, y)',
      teaser: '(3, 2) artinya maju 3 lalu naik 2. Urutannya setia: x dulu, y kemudian — jangan tertukar!' },
    { id: 'p2-073', k: 8, n: 3, judul: 'Empat Daerah Kuadran',
      teaser: 'Dua sumbu membagi bidang jadi 4 daerah: kanan-atas, kiri-atas, dan dua daerah lagi di bawah.' },
    { id: 'p2-074', k: 8, n: 4, judul: 'Menggambar Titik',
      teaser: 'Tandai (2, 5), (−3, 4), lalu (0, −2): setiap alamat hanya punya satu titik, tak pernah kembar.' },
    { id: 'p2-075', k: 8, n: 5, judul: 'Garis dari Tabel',
      teaser: 'Pilih x, hitung y, tandai titiknya, tarik garis lurus. Grafik lahir dari tabel yang tertib.' },
    { id: 'p2-076', k: 8, n: 6, judul: 'Kemiringan Garis',
      teaser: 'Garis yang naik 2 setiap maju 1 punya kemiringan 2. Makin besar kemiringannya, makin terjal jalurnya.' },
    { id: 'p2-077', k: 8, n: 7, judul: 'Grafik Perjalanan',
      teaser: 'Sumbu waktu dan jarak bercerita: garis mendatar artinya berhenti, garis miring artinya melaju. Grafik bisa bercerita!' },
    { id: 'p2-078', k: 8, n: 8, judul: 'Titik Potong Sumbu',
      teaser: 'Garis menyentuh sumbu y di tempat x = 0: itulah alamat awalnya. Banyak cerita dimulai dari titik potong.' },
    { id: 'p2-079', k: 8, n: 9, judul: 'Peta Harta Karun',
      teaser: 'X menandai lokasi! Dengan koordinat, harta karun paling tersembunyi pun ketahuan alamatnya.' },
    { id: 'p2-080', k: 8, n: 10, judul: 'Tantangan Alamat Hutan',
      teaser: 'Tandai titik, gambar garis, baca grafik perjalanan. Kuasai sumbu, dan seluruh hutan jadi peta yang ramah.' },

    /* --- k9: Statistika Kecil (10) --- */
    { id: 'p2-081', k: 9, n: 1, judul: 'Data: Kumpulan Angka',
      teaser: 'Data adalah kumpulan angka dari pengamatan: tinggi teman sekelas, cuaca harian. Kumpulan itu menyimpan cerita.' },
    { id: 'p2-082', k: 9, n: 2, judul: 'Mean: Rata-rata',
      teaser: 'Jumlahkan semua, bagi banyaknya data: itulah rata-rata. Ibarat membagi kue sama rata untuk semua tamu.' },
    { id: 'p2-083', k: 9, n: 3, judul: 'Median: Nilai Tengah',
      teaser: 'Susun data dari kecil ke besar, ambil yang di tengah: itulah median. Nilai tengah yang tak terseret ujung-ujung.' },
    { id: 'p2-084', k: 9, n: 4, judul: 'Modus: Paling Sering Muncul',
      teaser: 'Modus adalah nilai yang paling sering hadir — seperti rute favorit yang paling sering dilalui penduduk hutan.' },
    { id: 'p2-085', k: 9, n: 5, judul: 'Diagram Batang',
      teaser: 'Batang tinggi-rendah menggambarkan jumlah tiap kelompok. Sekali pandang, perbandingan langsung terbaca.' },
    { id: 'p2-086', k: 9, n: 6, judul: 'Diagram Garis',
      teaser: 'Titik yang dihubungkan garis menunjukkan perubahan: naik, turun, datar. Suhu dan antrean cocok digambar begini.' },
    { id: 'p2-087', k: 9, n: 7, judul: 'Diagram Lingkaran',
      teaser: 'Satu lingkaran dibagi irisan sesuai porsi tiap kelompok. Lingkaran penuh berarti 100 persen.' },
    { id: 'p2-088', k: 9, n: 8, judul: 'Membaca Tabel',
      teaser: 'Baris dan kolom menyimpan data rapi. Baca judul kolomnya dulu, tabel pun langsung bercerita.' },
    { id: 'p2-089', k: 9, n: 9, judul: 'Rentang Data',
      teaser: 'Terbesar dikurangi terkecil sama dengan rentang. Rentang kecil artinya data kompak, rentang besar artinya berjauhan.' },
    { id: 'p2-090', k: 9, n: 10, judul: 'Tantangan Data Hutan',
      teaser: 'Kumpulkan data daun, hitung mean-median-modus, gambar diagramnya. Jadilah peneliti muda di hutan simbol!' },

    /* --- k10: Peluang Dasar (10) --- */
    { id: 'p2-091', k: 10, n: 1, judul: 'Peluang Itu Apa?',
      teaser: 'Peluang menghitung kemungkinan: dari 0 (mustahil) sampai 1 (pasti). Di antaranya terbentang dunia "mungkin".' },
    { id: 'p2-092', k: 10, n: 2, judul: 'Koin: Dua Sisi',
      teaser: 'Koin punya dua sisi: peluang muncul angka adalah 1 dari 2, ditulis 1/2. Setengah kemungkinan, adil untuk dua pihak.' },
    { id: 'p2-093', k: 10, n: 3, judul: 'Dadu: Enam Kemungkinan',
      teaser: 'Dadu punya 6 sisi dan tiap sisi peluangnya 1/6. Angka 4 muncul sekali dari enam — jarang, tapi mungkin!' },
    { id: 'p2-094', k: 10, n: 4, judul: 'Pasti & Mustahil',
      teaser: 'Matahari terbit dari timur: pasti, peluangnya 1. Koin berdiri di sisinya: hampir mustahil, peluangnya 0.' },
    { id: 'p2-095', k: 10, n: 5, judul: 'Roda Putar Peluang',
      teaser: 'Roda dibagi irisan: makin lebar irisan sebuah warna, makin sering ia terpilih. Luas irisan menentukan peluang.' },
    { id: 'p2-096', k: 10, n: 6, judul: 'Kantong Kelereng',
      teaser: '3 kelereng merah dan 1 biru: peluang merah 3/4, peluang biru 1/4. Hitung isi kantong, peluang langsung terbaca.' },
    { id: 'p2-097', k: 10, n: 7, judul: 'Peluang sebagai Pecahan',
      teaser: 'Peluang selalu pecahan antara 0 dan 1. Semua kemungkinan dijumlahkan tepat 1 — tak lebih, tak kurang.' },
    { id: 'p2-098', k: 10, n: 8, judul: 'Mendaftar Kemungkinan',
      teaser: 'Dua koin dilempar bersama: daftar semua hasilnya dulu, hitung peluangnya kemudian. Lengkap, jelas, adil.' },
    { id: 'p2-099', k: 10, n: 9, judul: 'Peluang di Sekitar Kita',
      teaser: 'Prakiraan cuaca 80 persen artinya hampir pasti hujan. Peluang membantu kita memilih: bawa payung atau tidak.' },
    { id: 'p2-100', k: 10, n: 10, judul: 'Tantangan Peluang Hutan',
      teaser: 'Koin, dadu, roda, dan kantong kelereng berkumpul. Selesaikan semua hitungan kemungkinan, jadilah jagoan peluang!' },
  ];

  function topikKategori(k) { return TOPIK.filter(t => t.k === k); }
  function katById(id) { return KATEGORI.find(k => k.id === id) || null; }
  function topikById(id) { return TOPIK.find(t => t.id === id) || null; }
  function topikLain(id, arah) {                      // judul berikut/sebelumnya dalam penjuru yang sama
    const t = topikById(id);
    if (!t) return null;
    const daftar = topikKategori(t.k);
    const i = daftar.findIndex(x => x.id === id);
    return daftar[i + arah] || null;
  }

  return { KATEGORI, TOPIK, topikKategori, katById, topikById, topikLain };
})();
