window.P3 = (function () {
  'use strict';

  const KATEGORI = [
    { id: 'k1',  nama: 'Fungsi & Grafik', label: ['FUNGSI', 'GRAFIK'],
      sub: 'Mesin masukan-keluaran', jumlah: 10,
      color: '#7ff2d8', deep: '#1f9c84',
      ucap: ['Masukkan angka,', 'keluar kejutan!'] },
    { id: 'k2',  nama: 'Barisan & Deret', label: ['BARISAN', 'DERET'],
      sub: 'Pola bilangan berbaris', jumlah: 10,
      color: '#a5e8ff', deep: '#2a7fc0',
      ucap: ['Temukan', 'polanya!'] },
    { id: 'k3',  nama: 'Eksponen & Logaritma', label: ['PANGKAT', 'LOGARITMA'],
      sub: 'Tumbuh berlipat & jalan baliknya', jumlah: 10,
      color: '#ffe08a', deep: '#b8860b',
      ucap: ['Tumbuh', 'meledak-leledak!'] },
    { id: 'k4',  nama: 'Matriks & Sistem Persamaan', label: ['MATRIKS', 'SISTEM'],
      sub: 'Kotak angka yang bekerja sama', jumlah: 10,
      color: '#ff9db8', deep: '#b04a6e',
      ucap: ['Kotak angka', 'kerja tim!'] },
    { id: 'k5',  nama: 'Trigonometri', label: ['TRIGONO', 'METRI'],
      sub: 'Sisi & sudut segitiga', jumlah: 10,
      color: '#c8b6ff', deep: '#6a4fc0',
      ucap: ['Ukur yang', 'tak terjangkau!'] },
    { id: 'k6',  nama: 'Vektor & Geometri Ruang', label: ['VEKTOR', 'RUANG'],
      sub: 'Bilangan yang punya arah', jumlah: 10,
      color: '#9df2a8', deep: '#2a9c50',
      ucap: ['Panah punya', 'arah & besar!'] },
    { id: 'k7',  nama: 'Limit', label: ['LIMIT', 'MENUJU'],
      sub: 'Ke mana nilai bergerak', jumlah: 10,
      color: '#ffc48a', deep: '#b0622a',
      ucap: ['Makin dekat,', 'makin jelas!'] },
    { id: 'k8',  nama: 'Turunan', label: ['TURUNAN', 'LAJU'],
      sub: 'Laju perubahan sesaat', jumlah: 10,
      color: '#f2a8d8', deep: '#a83a78',
      ucap: ['Ukur lajunya', 'di tiap titik!'] },
    { id: 'k9',  nama: 'Integral', label: ['INTEGRAL', 'LUAS'],
      sub: 'Menjumlah potongan kecil', jumlah: 10,
      color: '#d4f28a', deep: '#6a9c2a',
      ucap: ['Potong kecil,', 'jumlah besar!'] },
    { id: 'k10', nama: 'Kombinatorika & Data', label: ['KEMUNGKINAN', 'DATA'],
      sub: 'Menghitung pilihan & membaca data', jumlah: 10,
      color: '#b8d8ff', deep: '#4a6fc0',
      ucap: ['Hitung semua', 'pilihannya!'] },
  ];

  const TOPIK = [

    { id: 'p3-001', k: 1, n: 1, judul: 'Mesin Fungsi',
      teaser: 'Ada mesin ajaib: masukkan bilangan, keluar bilangan baru. Aturannya tetap — masukan sama selalu menghasilkan keluaran yang sama. Itu rahasia fungsi!' },
    { id: 'p3-002', k: 1, n: 2, judul: 'Masukan & Keluaran',
      teaser: 'x masuk, f(x) keluar. Tulisan f(3) bukan f kali 3 — itu tanda "hasil mesin untuk masukan 3". Nama keren keluarannya!' },
    { id: 'p3-003', k: 1, n: 3, judul: 'Aturan Mesin',
      teaser: 'Mesin y = 2x menggandakan semua: masuk 3, keluar 6. Setiap mesin punya aturan yang bisa dibaca, ditiru, dan dipraktikkan.' },
    { id: 'p3-004', k: 1, n: 4, judul: 'Tabel Pasangan',
      teaser: 'Susun pasangan masukan-keluaran dalam tabel rapi: setiap x hanya punya satu teman y. Seperti daftar antre yang tak boleh ganda.' },
    { id: 'p3-005', k: 1, n: 5, judul: 'Titik di Bidang',
      teaser: 'Pasangan (2, 4) berubah jadi titik di bidang koordinat — alamat rumah setiap pasangan. Koordinat dari Hutan Simbol kini dipakai mesin!' },
    { id: 'p3-006', k: 1, n: 6, judul: 'Garis dari Mesin',
      teaser: 'Titik-titik mesin y = 2x berbaris rapi membentuk garis lurus. Sambungkan dengan tali — semuanya tunduk pada satu aturan!' },
    { id: 'p3-007', k: 1, n: 7, judul: 'Grafik Naik & Turun',
      teaser: 'Garis menanjak artinya keluaran makin besar; menurun artinya makin kecil. Grafik punya arah, dan arah itu bisa dibaca.' },
    { id: 'p3-008', k: 1, n: 8, judul: 'Jalur Bola Kuadrat',
      teaser: 'Bola dilempar melengkung anggun. Grafik y = x² membentuk lengkung simetris: sisi kiri dan kanan berhadapan seperti cermin!' },
    { id: 'p3-009', k: 1, n: 9, judul: 'Grafik Bercerita',
      teaser: 'Ember terisi air: garis naik lalu datar saat penuh. Perjalanan: naik, berhenti, naik lagi. Bentuk grafik menyimpan cerita!' },
    { id: 'p3-010', k: 1, n: 10, judul: 'Tantangan Lembah Mesin',
      teaser: 'Lima misi menantimu: tebak aturan mesin dari tabelnya, gambar grafiknya, baca ceritanya. Jadilah ahli mesin lembah!' },

    { id: 'p3-011', k: 2, n: 1, judul: 'Barisan: Pola Berbaris',
      teaser: '2, 4, 6, 8: barisan adalah bilangan yang berbaris dengan aturan tetap. Setiap anggota tahu jaraknya ke tetangganya!' },
    { id: 'p3-012', k: 2, n: 2, judul: 'Barisan Tambah',
      teaser: 'Tambah 3 tiap langkah: 5, 8, 11, 14. Beda antar tetangga selalu sama — itulah barisan aritmetika yang setia.' },
    { id: 'p3-013', k: 2, n: 3, judul: 'Barisan Gandakan',
      teaser: 'Kali 2 tiap langkah: 1, 2, 4, 8, 16. Tumbuhnya meledak-leledak! Coba lanjutkan: angka berikutnya jauh lebih besar.' },
    { id: 'p3-014', k: 2, n: 4, judul: 'Suku ke-n',
      teaser: 'Rumus 3n + 1 melompat langsung ke suku mana pun tanpa menghitung satu per satu. Suku ke-100? Tinggal masukkan 100!' },
    { id: 'p3-015', k: 2, n: 5, judul: 'Rahasia Pasangan',
      teaser: '1 + 2 + 3 + ... + 100: pasangkan ujung-ujungnya, tiap pasangan berjumlah 101, ada 50 pasangan. Jadi 101 × 50 = 5050!' },
    { id: 'p3-016', k: 2, n: 6, judul: 'Deret Gandakan',
      teaser: '1 + 2 + 4 + 8 + 16: jumlahnya selalu satu kurang dari anggota berikutnya. 1+2+4 = 7, dan 7 satu kurang dari 8!' },
    { id: 'p3-017', k: 2, n: 7, judul: 'Bilangan Segitiga',
      teaser: '1, 3, 6, 10: kursi berbaris mengerucut membentuk segitiga. Tambahkan baris baru, jumlahnya tumbuh teratur.' },
    { id: 'p3-018', k: 2, n: 8, judul: 'Bilangan Kuadrat',
      teaser: '1, 4, 9, 16: kotak yang sisinya tumbuh satu per satu. 3 × 3 = 9 — anggota barisan ini benar-benar berbentuk kotak!' },
    { id: 'p3-019', k: 2, n: 9, judul: 'Pola di Sekitar Kita',
      teaser: 'Kelopak bunga, tangga nada, tahun kabisat: barisan bersembunyi di mana-mana. Pemburu pola tak pernah kehabisan kejutan.' },
    { id: 'p3-020', k: 2, n: 10, judul: 'Tantangan Puncak Pola',
      teaser: 'Lanjutkan barisan, temukan rumusnya, lalu buktikan dengan mengecek dua suku. Puncak pola menunggu pendaki teliti!' },

    { id: 'p3-021', k: 3, n: 1, judul: 'Pangkat: Kali Berulang',
      teaser: '2³ = 2 × 2 × 2 = 8. Pangkat adalah perkalian yang diulang dengan setia. Angka kecil di atas itu ajakan mengali!' },
    { id: 'p3-022', k: 3, n: 2, judul: 'Ledakan Lipatan',
      teaser: 'Lipat kertas 42 kali: tebalnya menembus bulan! Pertumbuhan pangkat meledak — makin tinggi pangkatnya, makin luar biasa.' },
    { id: 'p3-023', k: 3, n: 3, judul: 'Kuadrat & Kubik',
      teaser: 'x² adalah luas persegi bersisi x; x³ adalah isi kubus bersisi x. Pangkat dua dan tiga sebenarnya tinggal di dalam bentuk!' },
    { id: 'p3-024', k: 3, n: 4, judul: 'Akar: Jalan Pulang',
      teaser: 'Akar pangkat dua mencari sisi asal: akar 49 = 7 karena 7 × 7 = 49. Akar adalah jalan pulang dari pangkat.' },
    { id: 'p3-025', k: 3, n: 5, judul: 'Logaritma Pencari Pangkat',
      teaser: 'log dua dari 8 bertanya: "2 pangkat berapa jadi 8?" Jawabnya 3! Logaritma adalah detektif pencari pangkat.' },
    { id: 'p3-026', k: 3, n: 6, judul: 'Pangkat Nol & Minus',
      teaser: '2⁰ = 1 dan 2⁻¹ = 1/2. Pangkat nol pasrah jadi satu; pangkat minus membelah. Tangga pangkat bisa naik dan turun!' },
    { id: 'p3-027', k: 3, n: 7, judul: 'Waktu Menggandakan',
      teaser: 'Koloni bakteri menggandakan tiap jam: 1, 2, 4, 8, 16. Waktu untuk menggandakan selalu sama — inilah denyut eksponen.' },
    { id: 'p3-028', k: 3, n: 8, judul: 'Bola Pantul Setengah',
      teaser: 'Bola memantul: 100, 50, 25, 12,5. Tingginya berkurang setengah tiap pantul. Turun pangkat = mengecil teratur!' },
    { id: 'p3-029', k: 3, n: 9, judul: 'Angka Raksasa & Mini',
      teaser: 'Bintang di alam semesta sekitar 10²²; lebar rambut sekitar 10⁻⁴ meter. Pangkat menyusun angka raksasa dan mini dengan rapi.' },
    { id: 'p3-030', k: 3, n: 10, judul: 'Tantangan Tangga Pangkat',
      teaser: 'Naik turun tangga pangkat, buru akar, jawab teka-teki logaritma. Penjuru tertinggi gunung menunggumu!' },

    { id: 'p3-031', k: 4, n: 1, judul: 'Kotak Angka Berdaya',
      teaser: 'Matriks adalah kotak-kotak angka rapi, seperti papan skor. Angka yang tertata tak sekadar diam — ia siap bekerja!' },
    { id: 'p3-032', k: 4, n: 2, judul: 'Alamat Baris-Kolom',
      teaser: 'Angka di baris 2, kolom 3 ditulis a₂₃. Baris dulu, kolom kemudian — seperti lantai dulu baru nomor kamarnya!' },
    { id: 'p3-033', k: 4, n: 3, judul: 'Menjumlah Sejawat',
      teaser: 'Kotak bertemu kotak sejawat: 2 + 1 = 3. Menjumlah matriks itu mudah — hitung tiap kotak dengan pasangannya!' },
    { id: 'p3-034', k: 4, n: 4, judul: 'Menggandakan Matriks',
      teaser: 'Semua kotak ikut dikali 2: resep yang sama, porsi dua kali lipat. Bilangan di depan matriks menyapa semuanya.' },
    { id: 'p3-035', k: 4, n: 5, judul: 'Baris Menyapa Kolom',
      teaser: 'Perkalian matriks: baris kiri menyapa kolom kanan, kalikan sejawat lalu jumlahkan. Sapaan paling tertib di gunung!' },
    { id: 'p3-036', k: 4, n: 6, judul: 'Dua Petunjuk Bertemu',
      teaser: 'x + y = 7 dan x − y = 1: dua petunjuk bersama menemukan x = 4 dan y = 3. Satu petunjuk kurang, dua petunjuk pas!' },
    { id: 'p3-037', k: 4, n: 7, judul: 'Titik Temu Dua Garis',
      teaser: 'Dua garis berpotongan di satu titik: itulah jawaban yang disetujui keduanya. Titik temu adalah tempat damai dua garis.' },
    { id: 'p3-038', k: 4, n: 8, judul: 'Matriks Penyimpan Data',
      teaser: 'Nilai 3 anak × 2 pelajaran tersusun rapi dalam matriks 3 × 2. Data yang tertata mudah dibaca, dicari, dan dijumlah!' },
    { id: 'p3-039', k: 4, n: 9, judul: 'Sistem Tiga Petunjuk',
      teaser: 'Tiga persamaan mencari tiga penemu x, y, z: kerja tim yang rapat. Petunjuk makin banyak, jawaban makin pasti.' },
    { id: 'p3-040', k: 4, n: 10, judul: 'Tantangan Papan Angka',
      teaser: 'Jumlahkan, gandakan, sapa baris-kolom, dan temukan titik temu. Papan angka gunung menantimu!' },

    { id: 'p3-041', k: 5, n: 1, judul: 'Nama Tiga Sisi',
      teaser: 'Segitiga siku punya alas, tegak, dan sisi miring (yang paling panjang). Kenali tiga sahabat ini, hitung jadi lebih mudah!' },
    { id: 'p3-042', k: 5, n: 2, judul: 'Tangga Bersandar',
      teaser: 'Tangen membandingkan tinggi dengan jarak: makin tinggi tangga bersandar, makin lebar jejak kakinya. Perbandingan yang setia!' },
    { id: 'p3-043', k: 5, n: 3, judul: 'Sinus & Cosinus',
      teaser: 'Sinus mengawinkan tinggi dengan sisi miring; cosinus mengawinkan alas dengan sisi miring. Dua sahabat sisi miring!' },
    { id: 'p3-044', k: 5, n: 4, judul: 'Perbandingan yang Setia',
      teaser: 'Segitiga siku sebangun: bentuk sama berarti perbandingan sama, walau ukurannya beda jauh. Kecil memimpin yang besar!' },
    { id: 'p3-045', k: 5, n: 5, judul: 'Tinggi Pohon Tanpa Memanjat',
      teaser: 'Ukur sudut dari jarak tertentu, pakai tangen, tinggi pohon terjawab! Trigonometri mengukur yang tak bisa disentuh.' },
    { id: 'p3-046', k: 5, n: 6, judul: 'Ayunan yang Berulang',
      teaser: 'Ayunan buah, riak laut, denyut jantung: gerak berulang digambarkan gelombang sinus. Naik-turun yang setia ritmenya!' },
    { id: 'p3-047', k: 5, n: 7, judul: 'Lingkaran yang Berputar',
      teaser: 'Titik berputar di roda: naik-turunnya adalah sinus, maju-mundurnya cosinus. Roda berputar, gelombang lahir!' },
    { id: 'p3-048', k: 5, n: 8, judul: 'Tiga Sudut Istimewa',
      teaser: '30°, 45°, 60°: perbandingannya bisa digambar, dihafal, dan dipakai berulang kali. Tiga sahabat paling sering disebut!' },
    { id: 'p3-049', k: 5, n: 9, judul: 'Riak Air Kolam',
      teaser: 'Riak air berulang: puncak ke puncak punya jarak tetap — panjang gelombang. Kolam adalah kelas gelombang terbuka!' },
    { id: 'p3-050', k: 5, n: 10, judul: 'Tantangan Pengukur Jauh',
      teaser: 'Ukur menara, sungai, dan jurang tanpa tali panjang: trigonometri adalah petakamu. Penjuru pengukur menantimu!' },

    { id: 'p3-051', k: 6, n: 1, judul: 'Bilangan Berarah',
      teaser: '5 langkah ke timur beda dengan 5 langkah ke barat: vektor punya besar DAN arah. Bilangan yang bisa menunjuk jalan!' },
    { id: 'p3-052', k: 6, n: 2, judul: 'Panah Perjalanan',
      teaser: 'Dari rumah ke sekolah: panah vektor menunjuk jalan paling langsung. Panah itu membawa dua informasi: sejauh mana dan ke arah mana.' },
    { id: 'p3-053', k: 6, n: 3, judul: 'Menyambung Panah',
      teaser: 'Jalan berturut disambung: dari ujung panah pertama ke ujung panah terakhir adalah jumlahnya. Berjalan bertahap, satu panah jawab!' },
    { id: 'p3-054', k: 6, n: 4, judul: 'Kembar & Lawan',
      teaser: 'Vektor kembar: panjang sama, arah sama. Vektor lawan: sama besar tapi berbalik — maju 3 dan mundur 3 saling membatalkan.' },
    { id: 'p3-055', k: 6, n: 5, judul: 'Vektor di Kisi Kotak',
      teaser: 'Kanan 3, naik 2: vektor (3, 2) hidup di kisi kotak. Dua angka saja sudah cukup untuk menunjuk arah!' },
    { id: 'p3-056', k: 6, n: 6, judul: 'Perahu Menyeberang',
      teaser: 'Dayung ke arah satu, deras sungai mendorong ke lain arah: dua panah berpadu, perahu meluncur miring. Hitung paduannya, sampai tepat tujuan!' },
    { id: 'p3-057', k: 6, n: 7, judul: 'Alamat di Ruang',
      teaser: 'Panjang, lebar, tinggi: burung yang terbang pun alamat tiga dimensi. Dunia sebenarnya hidup di ruang, bukan hanya di kertas!' },
    { id: 'p3-058', k: 6, n: 8, judul: 'Jarak Naik-Turun',
      teaser: 'Tangga dan lift: jarak di ruang dihitung tiga arah sekaligus. Naik, menyamping, maju — tiga langkah satu jarak.' },
    { id: 'p3-059', k: 6, n: 9, judul: 'Tiga Pandangan Satu Bentuk',
      teaser: 'Depan, atas, samping: satu bangunan, tiga gambar rahasia. Gabungkan ketiganya, bentuk aslinya terbongkar!' },
    { id: 'p3-060', k: 6, n: 10, judul: 'Tantangan Lintas Lembah',
      teaser: 'Petakan lintasan panah, gabungkan jalan berturut, temukan jalur paling cepat. Angkasa pegunungan menantimu!' },

    { id: 'p3-061', k: 7, n: 1, judul: 'Langkah Setengah',
      teaser: 'Menuju tembok berjarak 1: sisa langkah 1/2, lalu 1/4, lalu 1/8... tak pernah melewati tembok. Langkah mengecil, total menuju satu!' },
    { id: 'p3-062', k: 7, n: 2, judul: '0,9 lalu 0,99 lalu 0,999',
      teaser: 'Sembilan menempel terus: 0,9; 0,99; 0,999... makin dekat ke 1, sejauh mana pun tak melampaui. Dekat tanpa menyentuh!' },
    { id: 'p3-063', k: 7, n: 3, judul: 'Ke Mana Nilai Bergerak',
      teaser: 'Limit bertanya: bila langkah makin kecil, ke mana jawaban ini menuju? Limit mencari tujuan berkat pola hitungan, bukan menebak-nebak!' },
    { id: 'p3-064', k: 7, n: 4, judul: 'Menempel di Garis',
      teaser: 'Kurva mendekati garis bantu makin rapat tapi tak pernah menyentuhnya: garis itu namanya asimtot. Sahabat yang didekati terus!' },
    { id: 'p3-065', k: 7, n: 5, judul: 'Potongan Makin Halus',
      teaser: 'Bagi tali jadi potongan makin kecil, jumlah seluruh potongan tetap panjang aslinya. Mengecil tanpa berubah total!' },
    { id: 'p3-066', k: 7, n: 6, judul: 'Tangga Jadi Landai',
      teaser: 'Anak tangga makin banyak dan makin pipih: tangga menyamar jadi landai mulus. Gerbang menuju lereng kalkulus!' },
    { id: 'p3-067', k: 7, n: 7, judul: 'Kilas Makin Singkat',
      teaser: 'Hitung kecepatan dalam 1 jam, 1 menit, 1 detik, lalu 1 kilas mata: makin singkat, makin dekat ke laju sesaat.' },
    { id: 'p3-068', k: 7, n: 8, judul: 'Satu per n Menuju Nol',
      teaser: 'Satu dibagi dua, seratus, seribu: hasilnya makin menempel di nol. Pembagi makin besar, hasil makin kecil tanpa pernah minus!' },
    { id: 'p3-069', k: 7, n: 9, judul: 'Poligon Menyamar Bulat',
      teaser: 'Segi enam, dua belas, seratus sudut: makin banyak sudut, makin mirip lingkaran. Archimedes mendekati lingkaran dengan cara ini!' },
    { id: 'p3-070', k: 7, n: 10, judul: 'Tantangan Tepi Menuju',
      teaser: 'Kejar nilai yang bergerak: saat langkah makin kecil, jawaban makin jelas. Uji kemampuan mendekatmu di tepi gunung!' },

    { id: 'p3-071', k: 8, n: 1, judul: 'Laju yang Berubah',
      teaser: 'Air keran deras lalu pelan: laju perubahan bisa berubah-ubah. Turunan adalah alat mengukur laju di setiap saat!' },
    { id: 'p3-072', k: 8, n: 2, judul: 'Rata-rata vs Sesaat',
      teaser: 'Perjalanan 60 km dalam 1 jam: rata-rata 60. Tapi speedometer bergetar sepanjang jalan — laju sesaat bisa 40 bisa 80!' },
    { id: 'p3-073', k: 8, n: 3, judul: 'Garis Singgung',
      teaser: 'Garis yang menempel pas di satu titik kurva: kemiringannya adalah turunan kurva di titik itu. Penempel paling pas!' },
    { id: 'p3-074', k: 8, n: 4, judul: 'Turunan x2',
      teaser: 'Rahasia mudah: turunan x² adalah 2x. Pangkat turun ke depan jadi koefisien, lalu pangkatnya turun satu. Coba y = x²!' },
    { id: 'p3-075', k: 8, n: 5, judul: 'Menanjak & Menurun',
      teaser: 'Turunan positif berarti menanjak, negatif menurun, nol berhenti sejenak — biasanya di puncak atau lembah!' },
    { id: 'p3-076', k: 8, n: 6, judul: 'Puncak Air Ember',
      teaser: 'Kapan air ember paling tinggi? Cari titik dengan turunan nol — puncaknya ketemu! Turunan adalah pemburu puncak.' },
    { id: 'p3-077', k: 8, n: 7, judul: 'Dari Laju ke Percepatan',
      teaser: 'Turunkan dua kali: dari jarak lahir kecepatan, dari kecepatan lahir percepatan. Turunan bertingkat seperti tangga gunung!' },
    { id: 'p3-078', k: 8, n: 8, judul: 'Kurva Tersenyum',
      teaser: 'Kurva bentuk U punya titik terendah di dasar senyumnya. Turunan nol menemukannya — lembah tak bisa sembunyi!' },
    { id: 'p3-079', k: 8, n: 9, judul: 'Motor Berakselerasi',
      teaser: 'Motor berangkat makin kencang: percepatan adalah laju dari laju. Tiap detik kecepatannya bertambah — itu percepatan!' },
    { id: 'p3-080', k: 8, n: 10, judul: 'Tantangan Lereng Curam',
      teaser: 'Ukur kemiringan di tiap titik lereng, temukan puncak dan lembah. Turunan kompas pendaki kalkulus!' },

    { id: 'p3-081', k: 9, n: 1, judul: 'Menjumlah Potongan',
      teaser: 'Roti dipotong tipis-tipis lalu dijumlahkan kembali: totalnya tetap satu roti. Itulah jiwa integral — potong lalu jumlah!' },
    { id: 'p3-082', k: 9, n: 2, judul: 'Luas di Bawah Garis',
      teaser: 'Di bawah garis lurus terhampar persegi panjang rapi: luasnya panjang × lebar. Bentuk paling ramah untuk dihitung!' },
    { id: 'p3-083', k: 9, n: 3, judul: 'Potongan Makin Tipis',
      teaser: 'Makin tipis potongannya, makin pas luas di bawah kurva. Ribuan potongan tipis menyusun jawaban yang mulus!' },
    { id: 'p3-084', k: 9, n: 4, judul: 'Jalan Pulang Turunan',
      teaser: 'Turunan x² adalah 2x; maka 2x punya asal x². Integral adalah jalan pulang: mencari asal sebuah turunan!' },
    { id: 'p3-085', k: 9, n: 5, judul: 'Luas di Bawah Lengkung',
      teaser: 'Parabola melengkung anggun: integral menghitung luas di bawahnya tanpa menebak. Lengkung pun tak bisa sembunyi!' },
    { id: 'p3-086', k: 9, n: 6, judul: 'Jarak dari Grafik Laju',
      teaser: 'Luas di bawah grafik kecepatan sama dengan jarak yang ditempuh. Kecepatan yang dijumlah sepanjang waktu jadi jarak!' },
    { id: 'p3-087', k: 9, n: 7, judul: 'Huruf S Memanjang',
      teaser: 'Tanda integral adalah huruf S panjang dari kata "jumlah": ajakan menjumlah potongan-potongan kecil. Simbol paling anggun di matematika!' },
    { id: 'p3-088', k: 9, n: 8, judul: 'Tetesan Jadi Ember',
      teaser: 'Kran menetes sepanjang waktu: jumlah semua tetesan menjadi volume air di ember. Tetes kecil, akumulasi hebat!' },
    { id: 'p3-089', k: 9, n: 9, judul: 'Garis Rata dari Kurva',
      teaser: 'Ratakan luas kurva jadi persegi panjang: tingginya adalah nilai rata-rata kurva. Kurva bisa diratakan dengan adil!' },
    { id: 'p3-090', k: 9, n: 10, judul: 'Tantangan Lembah Luas',
      teaser: 'Potong, tipiskan, jumlahkan, temukan luas. Jadilah juru ukur lembah paling teliti di Pegunungan Pola!' },

    { id: 'p3-091', k: 10, n: 1, judul: 'Padanan Kemeja-Celana',
      teaser: '3 kemeja × 2 celana = 6 padanan. Setiap pilihan menyapa semua pilihan lainnya: aturan perkalian menghitung kemungkinan!' },
    { id: 'p3-092', k: 10, n: 2, judul: 'Barisan Antre Foto',
      teaser: '3 teman berbaris foto: 3 × 2 × 1 = 6 urutan berbeda. Yang pertama 3 pilihan, sisanya menyusul — urutan itu penting!' },
    { id: 'p3-093', k: 10, n: 3, judul: 'Memilih Teman Giliran',
      teaser: 'Pilih 2 dari 4 teman untuk giliran main: urutan tak penting, jadi hitungannya beda. Kombinasi adalah memilih tanpa memedulikan urutan!' },
    { id: 'p3-094', k: 10, n: 4, judul: 'Pohon Kemungkinan',
      teaser: 'Gambar cabang-cabang pilihan: pohon kemungkinan menampakkan semua jalur sekaligus. Tak ada kemungkinan yang lolos dari pohon!' },
    { id: 'p3-095', k: 10, n: 5, judul: 'Tanda Seru Faktorial',
      teaser: '4! = 4 × 3 × 2 × 1 = 24. Tanda seru itu pengganda berantai: mengurutkan 4 benda ada 24 cara!' },
    { id: 'p3-096', k: 10, n: 6, judul: 'Dua Kelompok Data',
      teaser: 'Dua kelompok dengan rata-rata sama bisa sangat berbeda: rentang membongkarnya. Rapat berarti seragam, menyebar berarti berjauhan!' },
    { id: 'p3-097', k: 10, n: 7, judul: 'Lima Angka Ringkas',
      teaser: 'Minimum, kuartil bawah, median, kuartil atas, maksimum: lima angka merangkum seluruh data. Ringkas tapi jujur!' },
    { id: 'p3-098', k: 10, n: 8, judul: 'Grafik yang Menipang',
      teaser: 'Sumbu dipangkas bisa bikin perubahan kecil terlihat heboh. Baca grafik dengan mata jernih: cek sumbunya dulu!' },
    { id: 'p3-099', k: 10, n: 9, judul: 'Peluang Dua Kejadian',
      teaser: 'Dua koin dilempar bersama: daftar dulu semua hasilnya dengan pohon, baru hitung peluangnya. Lengkap dulu, hitung kemudian!' },
    { id: 'p3-100', k: 10, n: 10, judul: 'Tantangan Puncak Data',
      teaser: 'Hitung padanan, susun barisan antre, gambar pohon, baca data dengan jernih. Puncak pamungkas Pegunungan Pola menantimu!' },
  ];

  function topikKategori(k) { return TOPIK.filter(t => t.k === k); }
  function katById(id) { return KATEGORI.find(k => k.id === id) || null; }
  function topikById(id) { return TOPIK.find(t => t.id === id) || null; }
  function topikLain(id, arah) {
    const t = topikById(id);
    if (!t) return null;
    const daftar = topikKategori(t.k);
    const i = daftar.findIndex(x => x.id === id);
    return daftar[i + arah] || null;
  }

  return { KATEGORI, TOPIK, topikKategori, katById, topikById, topikLain };
})();
